name: build-publish
on: [push]

jobs:
  test:
    name: build-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn install

      - run: yarn build

      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
